apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
  labels:
    app: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
        - name: student-app
          image: ghcr.io/skaur1604/module_6_part_3:2920f9e72b55f74b033a60160a46e6a9426b1dae
          ports:
            - containerPort: 80