apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
  labels:
    app: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
        - name: student-app
          image: ghcr.io/skaur1604/module_6_part_3:3b0d074c90406ff61ee0790d86dc9e40b2b92a97
          ports:
            - containerPort: 80