apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app
  labels:
    app: student-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-app
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
        - name: student-app
          image: ghcr.io/skaur1604/module_6_part_3:89947ef972d062ec48b8b75f9b4c140c9666f77b
          ports:
            - containerPort: 80